### ISSUE TITLE
Incorrect behavior for bold title and invalid SVG output

### ISSUE THREAD

**Issue by JasperCraeghs** [wallento/wavedrompy#16]
The JSON below doesn't produce the same output as wavedrom tool. When converting the SVG to PDF format with cairosvg in GitLab CI using a docker image the following Exception is raised and a blank canvas in PDF is generated:

wavedrompy: ![screenshot 15](https://user-images.githubusercontent.com/28319872/64374038-474a5f80-d023-11e9-8a46-3051d4f443c2.jpg)
wavedrom: ![screenshot 16](https://user-images.githubusercontent.com/28319872/64374050-4ca7aa00-d023-11e9-9eee-ecadec6970c7.jpg)

```json
{
    "signal": [
        {
            "wave": "|nh....nh.nhn.xnhnh..|."
        },
        {
            "wave": "x=.....=..=..x|=.=...=.",
            "data": [
                "Calib.",
                "Stat./Comm.",
                "N data nibbles",
                "CRC",
                "Pause",
                "Calib."
            ]
        },
        {
            "node": "...................1.2."
        }
    ],
    "edge": [
        "1<->2 Interrupt"
    ],
    "head": {
        "text": [
            "tspan",
            [
                "tspan",
                {
                    "font-weight": "bold"
                },
                "SENT message signal timing diagram"
            ]
        ]
    }
}
```
```
Exception occurred:
  File "/usr/local/lib/python3.7/dist-packages/cairosvg/parser.py", line 419, in __init__
    'No tag with id="{}" found.'.format(element_id))
TypeError: No tag with id="|||" found.
```
When the cariosvg Exception is not raised _(during a local build in docer)_, I end up with the following conversion to PDF:
<img src="https://user-images.githubusercontent.com/28319872/64374214-9f816180-d023-11e9-9ead-82cde7ea4f56.png" alt="invalid_diagram" width="44"/>

To me this looks related to https://github.com/bavovanachte/sphinx-wavedrom/issues/13. Can I expect a fix soon or should I resort to other means for the time being?

**Comment by wallento** [comment]
Hi,

I think you mixed the two images wavedrom vs. wavedrompy, right? Can you please update to the latest master, the title issue has been fixed the last couple of days.
The problem with cairo is related to that the first one is a gap. I think it is very easy to fix, but cannot promise it until Monday.

Cheers,
Stefan

**Comment by JasperCraeghs** [comment]
Hi,

Yes, I did mix them up. I edited the post to fix it. A release on Monday would be awesome!

Thank you very much already!

**Comment by wallento** [comment]
Fixed, tracked by `test/files/issue_16.json` and part of `wavedrompy:2.0.3.post1`

Thanks for reporting and have a good weekend!

**Comment by wallento** [comment]
@JasperCraeghs I have added infrastructure to automatically ensure that regression json files still render identically as wavedrom. Do you think you can contribute some from your project?

**Comment by JasperCraeghs** [comment]
I most likely do. I will look into this. Good weekend to you too!

**Comment by JasperCraeghs** [comment]
I can confirm that the fix works.
