### ISSUE TITLE
Ticks Not Rendered Correctly

### ISSUE THREAD

**Issue by MutantPlatypus** [wallento/wavedrompy#17]
I was trying to create a test step where the SVGs from wavedrom and wavedrompy are rasterized and compared and noticed a difference:  the tick marks come out very slightly wrong.  It's almost like the alpha for edges and the alpha for the fill of data regions are not the same between wavedrom and wavedrompy, or alphas are same and drawing order is different.  When rasterized, the differences are only in the RGB channels, though  The alpha channels match.

The differences in the below images have been enhanced (via `PIL.ImageOps.autocontrast`)

`issue_14.json` differences:
![issue_14_noAlphaDiff](https://user-images.githubusercontent.com/1389865/64587444-67ed1f00-d36d-11e9-9ac0-43642db1601d.png)
Original overlayed on difference:
![issue_14_differenceAndOriginalComposed](https://user-images.githubusercontent.com/1389865/64587443-67ed1f00-d36d-11e9-9cb0-81c8e5c7370e.png)

`tutorial_1.json` differences:
![tutorial_1_noAlphaDiff](https://user-images.githubusercontent.com/1389865/64587445-6885b580-d36d-11e9-9ced-92236e768ceb.png)
Original overlayed on differences:
![tutorial_1_differenceAndOriginalComposed](https://user-images.githubusercontent.com/1389865/64587475-83582a00-d36d-11e9-88e0-33261c6df342.png)

I'll generate the rest of these images and push them to the scratch branch of my fork tomorrow evening.

**Comment by wallento** [comment]
Hm, I think this can become tricky to fix, thanks for reporting and working on that!

**Comment by wallento** [comment]
Easier than I thought, I just made wrong assumptions before. Fixed in 0c49dfb, please confirm if it works, thanks!

**Comment by MutantPlatypus** [comment]
Yes, that fixed it.  All of the upstream tests now pass a raster comparison test with cairosvg.  Its a super aggressive test.  Nice work!  I'll toss over a pull request with that test soon.
