### ISSUE TITLE
Lanes for Regs Discrepancy between Editor and Py version

### ISSUE THREAD

**Issue by MadaniJo** [wallento/wavedrompy#22]
Dear Stefan,
 I see some differences between editor and python version. Do you have any clue where this could come from ?
Here a very simple register definition I used and the pictures generated are different, I noticed also that in the editor code 0 and 1 give a gray color where only code 1 gives gray for Py.
```
svg = wavedrom.render("""{"reg":[{"name":"rsv","attr":["RSV"],"bits":7,"type":1},{"name":"FDMA_EN","bits":1}],"config":{"bits":8,"lanes":1}}""")
```
Editor rendering:
<img width="626" alt="wave_editor" src="https://user-images.githubusercontent.com/34537722/65095921-b2b60900-d9f5-11e9-83c0-ee31f21e4efd.PNG">
Py rendering:
<img width="345" alt="wave_python" src="https://user-images.githubusercontent.com/34537722/65095962-d711e580-d9f5-11e9-9fc3-2883f2a2e0fd.PNG">
Scaling might also be an issue in Py.
Best regards,
Dan

**Comment by wallento** [comment]
Hi, thanks. I will look into it asap, but probably not before the weekend. Thanks for reporting!

**Comment by MadaniJo** [comment]
Guten Tag Stefan,

Sehn zie ein moglichkeit um das problem zu losen.
Ich weiss wochen end sind immer zu kurz :(.

Grusse,
Dan

**Comment by wallento** [comment]
Sorry, I will now get to it. There seems to be a fundamental issue that I need to solve.

**Comment by MadaniJo** [comment]
Ha ha this is less nice for you if you have to dig deep.
Try still to enjoy the weekend.
Rgds,
Daniel

**Comment by lepommosaure** [comment]
Hi, it seems that the bits and lanes attributes are ignored in Register mode:

`{
    "reg": [
        {
            "name": "WD10",
            "bits": 10
        },
        {
            "name": "WD16",
            "bits": 16
        },
        {
            "bits": 2
        }
    ],
    "config": {
        "lanes": 2,
        "bits": 28
    }
}`

gives with **wavedrompy**:
![image](https://user-images.githubusercontent.com/56764164/69248659-ee637f80-0bac-11ea-8db7-39859668b16b.png)

whereas in **wavedrom-editor**:
![image](https://user-images.githubusercontent.com/56764164/69248702-04714000-0bad-11ea-97d7-c413905d0f37.png)

**Comment by wallento** [comment]
Hi,
both are fixed now, sorry for the delay and thanks for your patience. This part will need some more attention soon, please open another ticket with other examples that fail, thanks!

Best,
Stefan

**Comment by MarekPikula** [comment]
Hi @wallento, when will this patch d46987f be released to pip as stable? It's problematic to use git version in my use case.
