### ISSUE TITLE
deprecated attrdict and PyPi version

### ISSUE THREAD

**Issue by Yinameah** [wallento/wavedrompy#38]
Hello,

I'm using wavedrompy in my mkdocs project, in a very satisfactory way, thanks for the nice work 🙏.

However, I started to have a crash recently, that is due to the combination of python3.10 upgrade and the attrdict dependency. With this error : `cannot import name 'Mapping' from 'collections'`

I saw here that the issue has been address with some workaround in 05b1220f870ae513b7a4d4dc73ca4741c66a6c08. However, it is not updated on PyPi yet. 

I quickly tested the master branch, and seems to work fine. Is there any plan to release a new version on PyPi ? Is there anything preventing the said release ?

**Comment by wallento** [comment]
Hi,
I just released it now as https://pypi.org/project/wavedrom/2.0.3.post3/
Thanks for your patience.
Best

**Comment by Yinameah** [comment]
Incredible. Thanks you very much !! (my mkdocs upgraded flawlessly :tada: )
