### ISSUE TITLE
[ Pull Request ] Allowing input from stdin

### ISSUE THREAD

**Issue by K4zuki** [wallento/wavedrompy#6]
I made a change to allow input from stdin like:
```
cat input.json | wavedrompy -s output.svg
```
via following commit:

https://github.com/K4zuki/wavedrompy/commit/e977fb9bd0bb5c66a9f7f3b00ba5345f1062bb4e

As the repo above is forked from a different repo, I am unable to raise a PR directory.
Could you please merge?

**Comment by wallento** [comment]
Hi, yes, I was planning to get it moved to another org. Let me do that first and then we can directly PR to that. Thanks!

**Comment by wallento** [comment]
Hi, I have done it slightly differently in 3dac659. It keeps the interface identical to the wavedrom cli where -i is always required. Despite I agree with you, that it should work that way you want it..
