### ISSUE TITLE
First Letter of Header and Footer Text Is Truncated

### ISSUE THREAD

**Issue by MutantPlatypus** [wallento/wavedrompy#7]
The first letter of header and footer text is not rendered in the SVG.  Adding a header and footer to the example in Readme.md as below reproduces the error.

```python
import wavedrom
svg = wavedrom.render("""
{ "signal": [
 { "name": "CK",   "wave": "P.......",                                              "period": 2  },
 { "name": "CMD",  "wave": "x.3x=x4x=x=x=x=x", "data": "RAS NOP CAS NOP NOP NOP NOP", "phase": 0.5 },
 { "name": "ADDR", "wave": "x.=x..=x........", "data": "ROW COL",                     "phase": 0.5 },
 { "name": "DQS",  "wave": "z.......0.1010z." },
 { "name": "DQ",   "wave": "z.........5555z.", "data": "D0 D1 D2 D3" }
],
"head":{
    "text": "WaveDrom example"
},
"foot":{
    "text": "Figure 100"
}
}""")
svg.saveas("demo1.svg")
```
Gives
```xml
            <text fill="#000" text-anchor="middle" x="320.0" xml:space="preserve" y="-33">
                <tspan>a</tspan>
                <tspan>v</tspan>
                <tspan>e</tspan>
                <tspan>D</tspan>
                <tspan>r</tspan>
                <tspan>o</tspan>
                <tspan>m</tspan>
                <tspan>
                </tspan>
                <tspan>e</tspan>
                <tspan>x</tspan>
                <tspan>a</tspan>
                <tspan>m</tspan>
                <tspan>p</tspan>
                <tspan>l</tspan>
                <tspan>e</tspan>
            </text>
```
![image](https://user-images.githubusercontent.com/1389865/63728900-59621c00-c833-11e9-9a6f-1503090669dc.png)

demo1.svg generated above attached in full: [demo1.zip](https://github.com/wallento/wavedrompy/files/3543431/demo1.zip)

**Comment by wallento** [comment]
That's strange, thanks for reporting, I will look into it!

**Comment by wallento** [comment]
I have fixed it in 5092dd7, can you please give it a try? Thanks

**Comment by wallento** [comment]
Hi, reopened on purpose?

**Comment by MutantPlatypus** [comment]
Yes.  I thought I could point to the commit and would get some options when clicking the close button.  I have since learned it has to be closed by a pull request into the main trunk.  (I think.  I'm still learning the terminology and workflow.)  I wasn't sure if you wanted to close it via the pull request so I just reopened it.  I see you are closing other issues in a similar way, so I'll just close it now.  Thanks for your help!

Confirmed fixed in 5092dd7.

**Comment by wallento** [comment]
Oh yeah, the workflows differ usually. I tend to use "close by commit" only for my own issues and let users confirm. Anyhow, I just this morning changed it to "I will close and users can re-open if they found the fix did not work". Anyhow, I am not religious about the workflow for this size of a project :)

**Comment by wallento** [comment]
And thanks a lot for reporting the various issues. It is very helpful!

In case you find time and are allowed to you may consider to share regression tests with me. Known wave descriptions that we can ensure with automatic tests will not be broken accidentally.

**Comment by MutantPlatypus** [comment]
I actually already took a peek at the regression tests, but didn't understand the Regression object after giving it 20 seconds of though so I tabled it for later.  I am definitely considering it, though.

**Comment by wallento** [comment]
Oh, yeah, you need to understand a bit of the internals. It would be great if you can share with me some "interesting" waves. The regression checks that they are rendered properly. Unfortunately there are no other regressions (yet)

**Comment by wallento** [comment]
This is now also tested in the regression tests. You can add more tests if you have similar to 0afc434!

**Comment by MutantPlatypus** [comment]
I'll try.  What has your workflow been for adding a running a test locally before pushing to the remote repository?  I see the .gitignore file has Spyder and Jupyter entries... are you using either of those?

**Comment by wallento** [comment]
I am rather conservative:

 - Create multiple virtual envs for different Python versions (I run them occasionally on Python 2.7 and Python 3.5)
 - `pip install -e .[test]` in each venv
 - `WAVEDROMDIR=path/to/wavedrom pytest -v` (mostly -k for some specific test I am fixing

Obviously this can be improved, but it is not painful enough for me to look into alternatives :)
