### ISSUE TITLE
Issue with empty string as name

### ISSUE THREAD

**Issue by JasperCraeghs** [wallento/wavedrompy#9]
Given the following json.
```
{ "signal":[
  {"name": "", "wave": "13.========4.1", "data": ["StartBit", "b7", "b6", "b5", "b4", "b3", "b2", "b1", "b0", "StopBit"]},
  {"name": "Frame format", "wave": "1=.==....|=3=..1", "data": ["Break", "ID", "DATA", "CRC", "ACK", "End of frame"]}
]}
```
One signal has an empty string as _name_, which causes the signal to not get generated. It only takes up some vertical space:

![image](https://user-images.githubusercontent.com/28319872/63860360-440efe00-c9a9-11e9-93b9-a3a5f7d2069f.png)

If that were the only signal, only a vertical dashed line would get generated by wavedrompy. 
wavedrom allows an empty string as name. I think it would be nice if wavedrompy would support this as well.

**Comment by wallento** [comment]
Interesting.. I think I can fix that tomorrow, thanks!

**Comment by wallento** [comment]
Fixed in ac20aba. Thanks again for reporting!

**Comment by wallento** [comment]
Can you confirm that the fix worked?

**Comment by JasperCraeghs** [comment]
Yes, the fix worked. Thank you! When do you plan to make a new release? I am patiently waiting on one.

**Comment by wallento** [comment]
There will be one today and another one next week. I am currently bringing in recent upstream changes.

**Comment by wallento** [comment]
I have just released 2.0.2 and plan to release 2.1.2 soon.
@JasperCraeghs and @MutantPlatypus can you both please check if `wavedrom>2.0.2` works for you? Thanks!

**Comment by JasperCraeghs** [comment]
It works for me.

**Comment by MutantPlatypus** [comment]
Works for me, too.
![demo-10](https://user-images.githubusercontent.com/1389865/64044155-2621d480-cb34-11e9-8aa4-1d84a1021f3c.png)
![demo-5](https://user-images.githubusercontent.com/1389865/64044159-26ba6b00-cb34-11e9-86fa-cc2866b911e6.png)
![demo-0](https://user-images.githubusercontent.com/1389865/64044158-2621d480-cb34-11e9-8966-4bf3ba88c3cf.png)
![demo+5](https://user-images.githubusercontent.com/1389865/64044157-2621d480-cb34-11e9-9540-cd27325d1c84.png)

![Empty Name and Phase Check](https://user-images.githubusercontent.com/1389865/64044350-887ad500-cb34-11e9-80bb-31fb575a6bb0.png)
